/**
 * MJCF Generator
 * Converts UnifiedRobotModel to MJCF XML format
 */
import { UnifiedRobotModel, Link, Joint, Material, VisualGeometry, CollisionGeometry, InertialProperties, GeometryType } from '../models/UnifiedRobotModel.js';

export interface MJCFExportOptions {
    modelName?: string;
}

const EXPORT_HEADER_COMMENT = `<!--
  Auto-generated by Attic Viewer
  GitHub: https://github.com/Atticlmr/attic_viewer
  Website: https://viewer.osaerialrobot.top
  Note: This file was automatically exported and is currently in testing.
-->`;

export class MJCFGenerator {
    static generate(model: UnifiedRobotModel, options?: MJCFExportOptions): string {
        const lines: string[] = [];

        // Skip XML declaration and comment to ensure compatibility with loaders
        const modelName = options?.modelName || model.name || 'robot';
        lines.push('<mujoco model="' + this.escapeXml(modelName) + '">');

        // Generate compiler options
        lines.push('  <compiler angle="radian" meshdir="assets" autolimits="true"/>');

        // Generate assets (materials, meshes)
        const assetsContent = this.generateAssets(model);
        if (assetsContent) {
            lines.push('  <asset>');
            lines.push(assetsContent);
            lines.push('  </asset>');
        }

        // Generate worldbody with all bodies
        lines.push('  <worldbody>');
        const worldbodyContent = this.generateWorldbody(model);
        lines.push(worldbodyContent);
        lines.push('  </worldbody>');

        // Generate actuator (if needed - for simulation)
        // Skip for now as it's not needed for visual representation

        // Generate equality constraints
        const equalityContent = this.generateEquality(model);
        if (equalityContent) {
            lines.push('  <equality>');
            lines.push(equalityContent);
            lines.push('  </equality>');
        }

        lines.push('</mujoco>');

        return lines.join('\n');
    }

    private static generateAssets(model: UnifiedRobotModel): string {
        const lines: string[] = [];

        // Generate materials
        for (const [name, material] of model.materials) {
            let matLine = '    <material name="' + this.escapeXml(name) + '"';
            if (material.color) {
                matLine += ' rgba="' +
                    (material.color.r || 0.8).toFixed(3) + ' ' +
                    (material.color.g || 0.8).toFixed(3) + ' ' +
                    (material.color.b || 0.8).toFixed(3) + ' ' +
                    ((material.rgba && material.rgba[3]) || 1.0).toFixed(3) + '"';
            }
            if (material.shininess) {
                matLine += ' shininess="' + material.shininess.toFixed(2) + '"';
            }
            if (material.specular) {
                matLine += ' specular="' + material.specular[0].toFixed(2) + '"';
            }
            matLine += '/>';
            lines.push(matLine);
        }

        // Generate material references from link visuals
        const materialSet = new Set<string>();
        for (const [name, link] of model.links) {
            for (const visual of link.visuals) {
                if (visual.userData && visual.userData.materialName) {
                    materialSet.add(visual.userData.materialName);
                }
            }
        }

        // Add materials from visuals that have rgba but no named material
        for (const [name, link] of model.links) {
            for (const visual of link.visuals) {
                if (visual.userData && visual.userData.rgba && !visual.userData.materialName) {
                    const matName = 'mat_' + link.name + '_' + visual.name;
                    const rgba = visual.userData.rgba;
                    let matLine = '    <material name="' + matName + '"';
                    matLine += ' rgba="' +
                        rgba.r.toFixed(3) + ' ' +
                        rgba.g.toFixed(3) + ' ' +
                        rgba.b.toFixed(3) + ' ' +
                        (rgba.a || 1.0).toFixed(3) + '"';
                    matLine += '/>';
                    lines.push(matLine);
                }
            }
        }

        // Note: Mesh files are referenced but not embedded in the XML
        // They need to be included in the assets folder separately

        return lines.length > 0 ? lines.join('\n') : '';
    }

    private static generateWorldbody(model: UnifiedRobotModel): string {
        const lines: string[] = [];
        const indent = '    ';

        // Find root links (links that are not children of any joint)
        const childLinks = new Set<string>();
        for (const [name, joint] of model.joints) {
            if (joint.child) {
                childLinks.add(joint.child);
            }
        }

        // Get root link
        let rootLinkName = model.rootLink;
        if (!rootLinkName) {
            for (const [name, link] of model.links) {
                if (!childLinks.has(name)) {
                    rootLinkName = name;
                    break;
                }
            }
        }

        // If still no root, use first link
        if (!rootLinkName && model.links.size > 0) {
            rootLinkName = Array.from(model.links.keys())[0];
        }

        // Build body hierarchy recursively
        if (rootLinkName) {
            const visited = new Set<string>();
            lines.push(this.generateBodyRecursive(model, rootLinkName, indent, visited));
        }

        // Add any floating bodies (not connected to root)
        for (const [name, link] of model.links) {
            if (!lines.join('\n').includes('name="' + name + '"')) {
                const visited = new Set<string>();
                lines.push(this.generateBodyRecursive(model, name, indent, visited));
            }
        }

        return lines.join('\n');
    }

    private static generateBodyRecursive(
        model: UnifiedRobotModel,
        bodyName: string,
        indent: string,
        visited: Set<string>
    ): string {
        if (visited.has(bodyName)) {
            return '';
        }
        visited.add(bodyName);

        const link = model.links.get(bodyName);
        if (!link) {
            return '';
        }

        const lines: string[] = [];
        const bodyIndent = indent;

        // Start body element
        lines.push(bodyIndent + '<body name="' + this.escapeXml(bodyName) + '" pos="0 0 0">');

        // Generate geoms for this body
        const geomIndent = bodyIndent + '  ';

        // Visual geometries
        for (const visual of link.visuals) {
            lines.push(this.generateGeom(visual, geomIndent, 'visual'));
        }

        // Collision geometries
        for (const collision of link.collisions) {
            lines.push(this.generateGeom(collision, geomIndent, 'collision'));
        }

        // Inertial
        if (link.inertial) {
            lines.push(this.generateInertial(link.inertial, geomIndent));
        }

        // Find and generate child bodies through joints
        const childJoints: Joint[] = [];
        for (const [jointName, joint] of model.joints) {
            if (joint.parent === bodyName) {
                childJoints.push(joint);
            }
        }

        // Sort joints by child name for consistent output
        childJoints.sort((a, b) => (a.child || '').localeCompare(b.child || ''));

        for (const joint of childJoints) {
            if (joint.child) {
                lines.push(this.generateJoint(joint, bodyIndent + '  '));
                const childBody = this.generateBodyRecursive(model, joint.child, bodyIndent + '  ', visited);
                if (childBody) {
                    lines.push(childBody);
                }
            }
        }

        lines.push(bodyIndent + '</body>');

        return lines.join('\n');
    }

    private static generateGeom(geom: VisualGeometry | CollisionGeometry, indent: string, type: 'visual' | 'collision'): string {
        const geometry = geom.geometry;
        if (!geometry) {
            return '';
        }

        let group = type === 'visual' ? '1' : '3';
        if (geom.userData && geom.userData.group !== undefined) {
            group = String(geom.userData.group);
        }

        let xml = indent + '<geom type="' + geometry.type + '"';

        // Size attribute
        if (geometry.type === 'box' && geometry.size) {
            // URDF box is full size, MJCF is half-size
            xml += ' size="' +
                ((geometry.size.x || 0.1) / 2).toFixed(4) + ' ' +
                ((geometry.size.y || 0.1) / 2).toFixed(4) + ' ' +
                ((geometry.size.z || 0.1) / 2).toFixed(4) + '"';
        } else if (geometry.type === 'sphere' && geometry.size && geometry.size.radius) {
            xml += ' size="' + geometry.size.radius.toFixed(4) + '"';
        } else if ((geometry.type === 'cylinder' || geometry.type === 'capsule') && geometry.size) {
            // MJCF cylinder is radius, half-height
            xml += ' size="' +
                (geometry.size.radius || 0.05).toFixed(4) + ' ' +
                ((geometry.size.height || 0.1) / 2).toFixed(4) + '"';
        } else if (geometry.type === 'mesh') {
            if (geometry.filename) {
                xml += ' mesh="' + this.escapeXml(this.getMeshBaseName(geometry.filename)) + '"';
            }
            if (geometry.meshScale) {
                xml += ' scale="' +
                    geometry.meshScale[0].toFixed(4) + ' ' +
                    geometry.meshScale[1].toFixed(4) + ' ' +
                    geometry.meshScale[2].toFixed(4) + '"';
            }
        }

        // Group
        xml += ' group="' + group + '"';

        // Origin
        if (geom.origin) {
            const hasXyz = geom.origin.xyz[0] !== 0 || geom.origin.xyz[1] !== 0 || geom.origin.xyz[2] !== 0;
            const hasRpy = geom.origin.rpy[0] !== 0 || geom.origin.rpy[1] !== 0 || geom.origin.rpy[2] !== 0;

            if (hasXyz || hasRpy) {
                xml += ' pos="' + geom.origin.xyz[0].toFixed(4) + ' ' +
                    geom.origin.xyz[1].toFixed(4) + ' ' +
                    geom.origin.xyz[2].toFixed(4) + '"';

                if (hasRpy) {
                    xml += ' euler="' + geom.origin.rpy[0].toFixed(4) + ' ' +
                        geom.origin.rpy[1].toFixed(4) + ' ' +
                        geom.origin.rpy[2].toFixed(4) + '"';
                }
            }
        }

        // Color/material for visual geoms
        if (type === 'visual' && geom.userData) {
            if (geom.userData.materialName) {
                xml += ' material="' + this.escapeXml(geom.userData.materialName) + '"';
            } else if (geom.userData.rgba) {
                const rgba = geom.userData.rgba;
                xml += ' rgba="' +
                    rgba.r.toFixed(3) + ' ' +
                    rgba.g.toFixed(3) + ' ' +
                    rgba.b.toFixed(3) + ' ' +
                    (rgba.a || 1.0).toFixed(3) + '"';
            }
        }

        xml += '/>';

        return xml;
    }

    private static generateInertial(inertial: InertialProperties, indent: string): string {
        let xml = indent + '<inertial>\n';

        // Mass
        xml += indent + '  <mass value="' + (inertial.mass || 0).toFixed(4) + '"/>\n';

        // Origin
        if (inertial.origin) {
            const hasXyz = inertial.origin.xyz[0] !== 0 || inertial.origin.xyz[1] !== 0 || inertial.origin.xyz[2] !== 0;
            const hasRpy = inertial.origin.rpy[0] !== 0 || inertial.origin.rpy[1] !== 0 || inertial.origin.rpy[2] !== 0;

            if (hasXyz || hasRpy) {
                xml += indent + '  <pos="' + inertial.origin.xyz[0].toFixed(4) + ' ' +
                    inertial.origin.xyz[1].toFixed(4) + ' ' +
                    inertial.origin.xyz[2].toFixed(4) + '"';

                if (hasRpy) {
                    xml += ' euler="' + inertial.origin.rpy[0].toFixed(4) + ' ' +
                        inertial.origin.rpy[1].toFixed(4) + ' ' +
                        inertial.origin.rpy[2].toFixed(4) + '"';
                }
                xml += '/>\n';
            }
        }

        // Diagonal inertia
        xml += indent + '  <diaginertia ixx="' + (inertial.ixx || 0.001).toFixed(6) + '" ';
        xml += 'iyy="' + (inertial.iyy || 0.001).toFixed(6) + '" ';
        xml += 'izz="' + (inertial.izz || 0.001).toFixed(6) + '"/>\n';

        xml += indent + '</inertial>';

        return xml;
    }

    private static generateJoint(joint: Joint, indent: string): string {
        // Convert URDF joint type to MJCF type
        let mjcfType: string;
        switch (joint.type) {
            case 'revolute':
                mjcfType = 'hinge';
                break;
            case 'prismatic':
                mjcfType = 'slide';
                break;
            case 'continuous':
                mjcfType = 'hinge';
                break;
            case 'fixed':
                // Fixed joints are not represented in MJCF
                return '';
            case 'floating':
                mjcfType = 'free';
                break;
            default:
                mjcfType = 'hinge';
        }

        let xml = indent + '<joint type="' + mjcfType + '"';

        // Name
        xml += ' name="' + this.escapeXml(joint.name) + '"';

        // Pos (origin in body coords)
        if (joint.origin) {
            const hasXyz = joint.origin.xyz[0] !== 0 || joint.origin.xyz[1] !== 0 || joint.origin.xyz[2] !== 0;
            const hasRpy = joint.origin.rpy[0] !== 0 || joint.origin.rpy[1] !== 0 || joint.origin.rpy[2] !== 0;

            if (hasXyz || hasRpy) {
                xml += ' pos="' + joint.origin.xyz[0].toFixed(4) + ' ' +
                    joint.origin.xyz[1].toFixed(4) + ' ' +
                    joint.origin.xyz[2].toFixed(4) + '"';

                if (hasRpy) {
                    xml += ' euler="' + joint.origin.rpy[0].toFixed(4) + ' ' +
                        joint.origin.rpy[1].toFixed(4) + ' ' +
                        joint.origin.rpy[2].toFixed(4) + '"';
                }
            }
        }

        // Axis (for hinge and slide joints)
        if (joint.axis && (joint.type === 'revolute' || joint.type === 'prismatic' || joint.type === 'continuous')) {
            xml += ' axis="' + joint.axis.xyz[0].toFixed(4) + ' ' +
                joint.axis.xyz[1].toFixed(4) + ' ' +
                joint.axis.xyz[2].toFixed(4) + '"';
        }

        // Limits (range in MJCF)
        if (joint.limits && joint.type !== 'continuous' && joint.type !== 'fixed') {
            xml += ' range="' + (joint.limits.lower || -Math.PI).toFixed(4) + ' ' +
                (joint.limits.upper || Math.PI).toFixed(4) + '"';

            if (joint.limits.effort !== null && joint.limits.effort !== undefined) {
                xml += ' armature="' + joint.limits.effort.toFixed(2) + '"';
            }
            if (joint.limits.velocity !== null && joint.limits.velocity !== undefined) {
                xml += ' ctrlrange="0 ' + joint.limits.velocity.toFixed(2) + '"';
            }
        }

        // For continuous joints, set range to full rotation
        if (joint.type === 'continuous') {
            xml += ' range="-3.141592653589793 3.141592653589793"';
        }

        xml += '/>';

        return xml;
    }

    private static generateEquality(model: UnifiedRobotModel): string {
        const lines: string[] = [];

        // Convert constraints to MJCF equality elements
        for (const [name, constraint] of model.constraints) {
            switch (constraint.type) {
                case 'connect':
                    let connectLine = '    <connect body1="' + this.escapeXml(constraint.body1 || '') + '"';
                    connectLine += ' body2="' + this.escapeXml(constraint.body2 || '') + '"';
                    if (constraint.anchor) {
                        connectLine += ' anchor="' + constraint.anchor[0].toFixed(4) + ' ' +
                            constraint.anchor[1].toFixed(4) + ' ' +
                            constraint.anchor[2].toFixed(4) + '"';
                    }
                    connectLine += '/>';
                    lines.push(connectLine);
                    break;

                case 'weld':
                    let weldLine = '    <weld body1="' + this.escapeXml(constraint.body1 || '') + '"';
                    weldLine += ' body2="' + this.escapeXml(constraint.body2 || '') + '"';
                    if (constraint.anchor) {
                        weldLine += ' anchor="' + constraint.anchor[0].toFixed(4) + ' ' +
                            constraint.anchor[1].toFixed(4) + ' ' +
                            constraint.anchor[2].toFixed(4) + '"';
                    }
                    weldLine += '/>';
                    lines.push(weldLine);
                    break;

                case 'joint':
                    let jointLine = '    <joint joint1="' + this.escapeXml(constraint.joint1 || '') + '"';
                    jointLine += ' joint2="' + this.escapeXml(constraint.joint2 || '') + '"';
                    if (constraint.polycoef) {
                        jointLine += ' polycoef="' + constraint.polycoef.join(' ') + '"';
                    }
                    jointLine += '/>';
                    lines.push(jointLine);
                    break;

                case 'distance':
                    let distLine = '    <distance body1="' + this.escapeXml(constraint.body1 || '') + '"';
                    distLine += ' body2="' + this.escapeXml(constraint.body2 || '') + '"';
                    if (constraint.distance !== null && constraint.distance !== undefined) {
                        distLine += ' distance="' + constraint.distance.toFixed(4) + '"';
                    }
                    distLine += '/>';
                    lines.push(distLine);
                    break;
            }
        }

        return lines.length > 0 ? lines.join('\n') : '';
    }

    private static getMeshBaseName(filename: string): string {
        if (!filename) return '';
        // Remove path and extension
        const parts = filename.split('/');
        const name = parts[parts.length - 1];
        return name.replace(/\.[^/.]+$/, '');
    }

    private static escapeXml(str: string): string {
        if (!str) return '';
        return str
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&apos;');
    }
}
