/**
 * URDF Generator
 * Converts UnifiedRobotModel to URDF XML format
 */
import { UnifiedRobotModel, Link, Joint, Material, VisualGeometry, CollisionGeometry, InertialProperties, GeometryType } from '../models/UnifiedRobotModel.js';

export interface URDFExportOptions {
    modelName?: string;
    packageName?: string;
}

type RgbaLike = {
    r: number;
    g: number;
    b: number;
    a?: number;
};

function getUserDataRgba(value: unknown): RgbaLike | null {
    if (!value || typeof value !== 'object') {
        return null;
    }

    const candidate = value as Partial<RgbaLike>;
    if (typeof candidate.r !== 'number' || typeof candidate.g !== 'number' || typeof candidate.b !== 'number') {
        return null;
    }

    return {
        r: candidate.r,
        g: candidate.g,
        b: candidate.b,
        a: typeof candidate.a === 'number' ? candidate.a : 1
    };
}

const EXPORT_HEADER_COMMENT = `<!--
  Auto-generated by Attic Viewer
  GitHub: https://github.com/Atticlmr/attic_viewer
  Website: https://viewer.osaerialrobot.top
  Note: This file was automatically exported and is currently in testing.
-->`;

export class URDFGenerator {
    private static currentPackageName: string = '';

    static generate(model: UnifiedRobotModel, options?: URDFExportOptions): string {
        const lines: string[] = [];
        
        // Store package name for use in mesh path generation
        this.currentPackageName = options?.packageName || options?.modelName || model.name || 'robot';

        // Skip XML declaration and comment to ensure compatibility with loaders
        const robotName = options?.modelName || model.name || 'robot';
        lines.push('<robot name="' + this.escapeXml(robotName) + '">');

        // Generate materials first (URDF requires material defined before use)
        if (model.materials && model.materials.size > 0) {
            for (const [name, material] of model.materials) {
                lines.push(this.generateMaterial(material));
            }
        }

        // Generate links
        for (const [name, link] of model.links) {
            lines.push(this.generateLink(link));
        }

        // Generate joints
        for (const [name, joint] of model.joints) {
            lines.push(this.generateJoint(joint));
        }

        lines.push('</robot>');

        return lines.join('\n');
    }

    private static generateMaterial(material: Material): string {
        const indent = '  ';
        let xml = indent + '<material name="' + this.escapeXml(material.name) + '">\n';

        if (material.color) {
            xml += indent + '  <color rgba="' +
                (material.color.r || 0.8).toFixed(3) + ' ' +
                (material.color.g || 0.8).toFixed(3) + ' ' +
                (material.color.b || 0.8).toFixed(3) + ' ' +
                ((material.rgba && material.rgba[3]) || 1.0).toFixed(3) + '"/>\n';
        }

        if (material.texture) {
            xml += indent + '  <texture filename="' + this.escapeXml(material.texture) + '"/>\n';
        }

        xml += indent + '</material>';
        return xml;
    }

    private static generateLink(link: Link): string {
        const indent = '  ';
        let xml = indent + '<link name="' + this.escapeXml(link.name) + '">\n';

        // Generate visual
        for (const visual of link.visuals) {
            xml += this.generateVisual(visual, indent + '  ');
        }

        // Generate collision
        for (const collision of link.collisions) {
            xml += this.generateCollision(collision, indent + '  ');
        }

        // Generate inertial
        if (link.inertial) {
            xml += this.generateInertial(link.inertial, indent + '  ');
        }

        xml += indent + '</link>';
        return xml;
    }

    private static generateVisual(visual: VisualGeometry, indent: string): string {
        let xml = indent + '<visual>\n';

        // Origin
        if (visual.origin) {
            xml += this.generateOrigin(visual.origin, indent + '  ');
        }

        // Geometry
        if (visual.geometry) {
            xml += this.generateGeometry(visual.geometry, indent + '  ');
        }

        // Material
        if (visual.material) {
            xml += indent + '  <material name="' + this.escapeXml(visual.material.name) + '"/>\n';
        } else if (visual.userData) {
            const rgba = getUserDataRgba(visual.userData.rgba);
            if (!rgba) {
                xml += indent + '</visual>';
                return xml;
            }
            xml += indent + '  <material>\n';
            xml += indent + '    <color rgba="' +
                rgba.r.toFixed(3) + ' ' +
                rgba.g.toFixed(3) + ' ' +
                rgba.b.toFixed(3) + ' ' +
                (rgba.a || 1.0).toFixed(3) + '"/>\n';
            xml += indent + '  </material>\n';
        }

        xml += indent + '</visual>';
        return xml;
    }

    private static generateCollision(collision: CollisionGeometry, indent: string): string {
        let xml = indent + '<collision>\n';

        // Origin
        if (collision.origin) {
            xml += this.generateOrigin(collision.origin, indent + '  ');
        }

        // Geometry
        if (collision.geometry) {
            xml += this.generateGeometry(collision.geometry, indent + '  ');
        }

        xml += indent + '</collision>';
        return xml;
    }

    private static generateGeometry(geometry: GeometryType, indent: string): string {
        let xml = indent + '<geometry>\n';

        switch (geometry.type) {
            case 'box':
                if (geometry.size) {
                    xml += indent + '  <box size="' +
                        (geometry.size.x || 0.1).toFixed(4) + ' ' +
                        (geometry.size.y || 0.1).toFixed(4) + ' ' +
                        (geometry.size.z || 0.1).toFixed(4) + '"/>\n';
                }
                break;

            case 'sphere':
                if (geometry.size && geometry.size.radius) {
                    xml += indent + '  <sphere radius="' + geometry.size.radius.toFixed(4) + '"/>\n';
                }
                break;

            case 'cylinder':
                if (geometry.size) {
                    xml += indent + '  <cylinder length="' +
                        (geometry.size.height || 0.1).toFixed(4) + '" radius="' +
                        (geometry.size.radius || 0.05).toFixed(4) + '"/>\n';
                }
                break;

            case 'capsule':
                if (geometry.size) {
                    xml += indent + '  <cylinder length="' +
                        (geometry.size.height || 0.1).toFixed(4) + '" radius="' +
                        (geometry.size.radius || 0.05).toFixed(4) + '"/>\n';
                }
                break;

            case 'mesh':
                if (geometry.filename) {
                    const meshFilename = this.convertMeshPath(geometry.filename);
                    xml += indent + '  <mesh filename="' + this.escapeXml(meshFilename) + '"/>\n';
                    if (geometry.meshScale) {
                        xml += indent + '  <mesh scale="' +
                            geometry.meshScale[0].toFixed(4) + ' ' +
                            geometry.meshScale[1].toFixed(4) + ' ' +
                            geometry.meshScale[2].toFixed(4) + '"/>\n';
                    }
                }
                break;

            default:
                console.warn('Unknown geometry type:', geometry.type);
        }

        xml += indent + '</geometry>';
        return xml;
    }

    private static generateInertial(inertial: InertialProperties, indent: string): string {
        let xml = indent + '<inertial>\n';

        // Mass
        xml += indent + '  <mass value="' + (inertial.mass || 0).toFixed(4) + '"/>\n';

        // Origin
        if (inertial.origin) {
            xml += this.generateOrigin(inertial.origin, indent + '  ');
        }

        // Inertia
        xml += indent + '  <inertia ixx="' + (inertial.ixx || 0).toFixed(6) + '" ';
        xml += 'iyy="' + (inertial.iyy || 0).toFixed(6) + '" ';
        xml += 'izz="' + (inertial.izz || 0).toFixed(6) + '" ';
        xml += 'ixy="' + (inertial.ixy || 0).toFixed(6) + '" ';
        xml += 'ixz="' + (inertial.ixz || 0).toFixed(6) + '" ';
        xml += 'iyz="' + (inertial.iyz || 0).toFixed(6) + '"/>\n';

        xml += indent + '</inertial>';
        return xml;
    }

    private static generateJoint(joint: Joint): string {
        const indent = '  ';
        let xml = indent + '<joint name="' + this.escapeXml(joint.name) + '" type="' + joint.type + '">\n';

        // Parent
        if (joint.parent) {
            xml += indent + '  <parent link="' + this.escapeXml(joint.parent) + '"/>\n';
        }

        // Child
        if (joint.child) {
            xml += indent + '  <child link="' + this.escapeXml(joint.child) + '"/>\n';
        }

        // Origin
        if (joint.origin) {
            xml += this.generateOrigin(joint.origin, indent + '  ');
        }

        // Axis
        if (joint.axis && joint.type !== 'fixed' && joint.type !== 'continuous') {
            xml += indent + '  <axis xyz="' +
                (joint.axis.xyz[0] || 0).toFixed(4) + ' ' +
                (joint.axis.xyz[1] || 0).toFixed(4) + ' ' +
                (joint.axis.xyz[2] || 1).toFixed(4) + '"/>\n';
        }

        // Limits
        if (joint.limits && joint.type !== 'fixed' && joint.type !== 'continuous') {
            xml += indent + '  <limit lower="' + (joint.limits.lower || -Math.PI).toFixed(4) + '" ';
            xml += 'upper="' + (joint.limits.upper || Math.PI).toFixed(4) + '" ';
            if (joint.limits.effort !== null && joint.limits.effort !== undefined) {
                xml += 'effort="' + joint.limits.effort.toFixed(2) + '" ';
            }
            if (joint.limits.velocity !== null && joint.limits.velocity !== undefined) {
                xml += 'velocity="' + joint.limits.velocity.toFixed(2) + '" ';
            }
            xml = xml.trimEnd() + '/>\n';
        }

        xml += indent + '</joint>';
        return xml;
    }

    private static generateOrigin(origin: { xyz: number[], rpy: number[] }, indent: string): string {
        const hasXyz = origin.xyz && (origin.xyz[0] !== 0 || origin.xyz[1] !== 0 || origin.xyz[2] !== 0);
        const hasRpy = origin.rpy && (origin.rpy[0] !== 0 || origin.rpy[1] !== 0 || origin.rpy[2] !== 0);

        if (!hasXyz && !hasRpy) {
            return '';
        }

        let xml = indent + '<origin';
        if (hasXyz) {
            xml += ' xyz="' + origin.xyz[0].toFixed(4) + ' ' + origin.xyz[1].toFixed(4) + ' ' + origin.xyz[2].toFixed(4) + '"';
        }
        if (hasRpy) {
            xml += ' rpy="' + origin.rpy[0].toFixed(4) + ' ' + origin.rpy[1].toFixed(4) + ' ' + origin.rpy[2].toFixed(4) + '"';
        }
        xml += '/>\n';
        return xml;
    }

    private static convertMeshPath(filename: string): string {
        if (!filename) return filename;
        
        // Keep the original mesh path as-is, just copy to assets folder
        return filename;
    }

    private static escapeXml(str: string): string {
        if (!str) return '';
        return str
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&apos;');
    }
}
